// Code generated by goctl. DO NOT EDIT.
package types

type Course struct {
	Id          int64       `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Classify    string      `json:"classify"`
	GenderLimit int         `json:"genderLimit"`
	MemberLimit MemberLimit `json:"memberLimit"`
	StartTime   int64       `json:"startTime"`
	Credit      int         `json:"credit"`
	TeacherName string      `json:"teacherName"`
}

type CreateSelectionReq struct {
	Name         string `json:"name"`
	MaxCredit    int    `json:"maxCredit,range=(0:12]"`
	StartTime    int64  `json:"startTime"`
	EndTime      int64  `json:"endTime"`
	Notification string `json:"notification"`
}

type EditSelectionReq struct {
	Id int64 `path:"id"`
	CreateSelectionReq
}

type MemberLimit struct {
	MaleCount   int `json:"maleCount"`
	FemaleCount int `json:"femaleCount"`
}

type MineCourseReply struct {
	List []*Course `json:"list"`
}

type SelectCourseId struct {
	Id int64 `path:"id"`
}

type SelectionAddCourseReq struct {
	SelectionId int64              `path:"selectionId"`
	List        []*SelectionCourse `json:"list"`
}

type SelectionCourse struct {
	CourseId  int64 `json:"courseId"`
	TeacherId int64 `json:"teacherId"`
}

type SelectionIdReq struct {
	Id int64 `path:"id"`
}

type SelectionReply struct {
	Name         string    `json:"name"`
	MaxCredit    int       `json:"maxCredit"`
	StartTime    int64     `json:"startTime"`
	EndTime      int64     `json:"endTime"`
	Notification string    `json:"notification"`
	CourseList   []*Course `json:"courseList"`
}
