// Code generated by goctl. DO NOT EDIT.
package types

type AddCourseReq struct {
	Course
}

type Course struct {
	Name        string       `json:"name"`
	Description string       `json:"description,optional"`
	Classify    string       `json:"classify,options=天文|地理|数学|物理|机械|航天|医学|信息|互联网|计算机"`
	GenderLimit int          `json:"genderLimit,options=0|1|2"`
	MemberLimit *MemberLimit `json:"memberLimit,optional"`
	StartTime   int64        `json:"startTime"`
	Credit      int          `json:"credit,range=(0,6]"`
}

type CourseInfoReply struct {
	Id int64 `json:"id"`
	Course
}

type CourseInfoReq struct {
	Id int64 `path:"id"`
}

type CourseListReply struct {
	CurrentPage int       `json:"currentPage"`
	Size        int       `json:"size"`
	CursorId    int64     `json:"cursorId"`
	HasMore     bool      `json:"hasMore"`
	List        []*Course `json:"list"`
}

type CourseListReq struct {
	Page     int   `json:"page,range=(0:]"`
	Size     int   `json:"size,range=(0:]"`
	CursorId int64 `json:"cursorId,optional"`
}

type DeleteCourseReq struct {
	Id int64 `path:"id"`
}

type EditCourseReq struct {
	Id int64 `path:"id"`
	Course
}

type MemberLimit struct {
	MeleCount   int `json:"meleCount"`
	FemaleCount int `json:"femaleCount"`
}
