// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	Auth "hey-go-zero/service/user/api/internal/handler/Auth"
	noAuth "hey-go-zero/service/user/api/internal/handler/noAuth"
	"hey-go-zero/service/user/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: noAuth.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: noAuth.LoginHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/user/info/self",
				Handler: Auth.UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/path",
				Handler: Auth.UserInfoEditHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
