// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReply struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender string `json:"gender"`
	Role   string `json:"role"`
}

type UserInfoReq struct {
	Name   string `json:"name,optional"`
	Gender string `json:"gender,optional"`
}

type UserLoginReply struct {
	Id       int64  `json:"id"`
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
}

type UserLoginReq struct {
	Username string `json:"username"`
	Passowrd string `json:"password"`
}

type UserRegisterReq struct {
	Username string `json:"username"`
	Passowrd string `json:"password"`
	Role     string `json:"role,options=student|teacher"`
}
