//  Copyright [2020] [hey-go-zero]
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReply struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	Gender   string `json:"gender"`
	Birthday string `json:"birthday"`
	Role     string `json:"role"`
}

type UserInfoReq struct {
	Name     string `json:"name,optional"`
	Gender   string `json:"gender,optional"`
	Birthday string `json:"birthday"`
}

type UserLoginReply struct {
	Id       string `json:"id"`
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
}

type UserLoginReq struct {
	Username string `json:"username"`
	Passowrd string `json:"passowrd"`
	Role     string `json:"role,options=student|teacher"`
}

type UserRegisterReq struct {
	Username string `json:"username"`
	Passowrd string `json:"passowrd"`
	Role     string `json:"role,options=student|teacher"`
}
