// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReply struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	Gender   string `json:"gender"`
	Birthday string `json:"birthday"`
	Role     string `json:"role"`
}

type UserInfoReq struct {
	Name     string `json:"name,optional"`
	Gender   string `json:"gender,optional"`
	Birthday string `json:"birthday"`
}

type UserLoginReply struct {
	Id       string `json:"id"`
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
}

type UserLoginReq struct {
	Username string `json:"username"`
	Passowrd string `json:"passowrd"`
	Role     string `json:"role,options=student|teacher"`
}

type UserRegisterReq struct {
	Username string `json:"username"`
	Passowrd string `json:"passowrd"`
	Role     string `json:"role,options=student|teacher"`
}
